ALTER TABLE Client
MODIFY clientID int(11) AUTO_INCREMENT;

ALTER TABLE Participant
MODIFY partID int(11) AUTO_INCREMENT;

ALTER TABLE LandOwner
MODIFY landID int(11) AUTO_INCREMENT;

ALTER TABLE LocalAuthority
MODIFY authID int(11) AUTO_INCREMENT;

ALTER TABLE Supplier
MODIFY supplierID int(11) AUTO_INCREMENT;

ALTER TABLE Event
MODIFY eventID int(11) AUTO_INCREMENT;

ALTER TABLE Register
MODIFY partID int(11) AUTO_INCREMENT;

ALTER TABLE LocalAuthorityEvent
MODIFY authID int(11) AUTO_INCREMENT;


ALTER TABLE EventSupplier
MODIFY supplierID int(11) AUTO_INCREMENT;


ALTER TABLE Staff
MODIFY staffID int(11) AUTO_INCREMENT;

ALTER TABLE EventStaff
MODIFY staffID int(11) AUTO_INCREMENT;


ALTER TABLE Sponsor
MODIFY sponsorID int(11) AUTO_INCREMENT;

ALTER TABLE EventStaff
MODIFY staffID int(11) AUTO_INCREMENT;
